<a href="https://colab.research.google.com/github/julianogueira3/Trabalho_mba_deeplearning/blob/main/trabalho_mba_deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introdução a modelos de deep learning Turma 9
#JÚLIA NOGUEIRA - 2427399
#JARLAN SILVA - 2427608
#ARTUR RODRIGUES - 2427753
#ISMAEL GÓES - 2428140
#Introdução: Sistema de Diagnóstico e Intervenção Educacional Baseado em IA
1. O que fizemos?
Desenvolvemos um ecossistema computacional integrado que une análise de dados (Pandas), Inteligência Artificial Generativa (LLM via Hugging Face) e automação de relatórios (ReportLab). O sistema processa indicadores de desempenho escolar (SAEB e taxas de alfabetização) e os cruza com informações qualitativas de infraestrutura para gerar planos de ação personalizados para escolas públicas.

2. Metodologia
O projeto foi estruturado em quatro pilares técnicos:

Tratamento de Dados: Utilização da biblioteca Pandas para filtrar e agregar microdados educacionais, permitindo identificar rapidamente as unidades escolares com maiores desafios.

Contextualização Híbrida: Criação de uma lógica de "Contexto Automático" que traduz números brutos em descritores textuais (ex: transformando uma nota baixa em "Desempenho muito baixo no SAEB").

Engenharia de Prompt e LLM: Integração com o modelo Qwen 2.5 7B através da API de Inferência do Hugging Face. Configuramos a IA para atuar como um "Especialista em Gestão Educacional", garantindo respostas técnicas e focadas em intervenção prática.

Persistência e Saída: Implementação de um módulo de histórico para rastreio de diagnósticos e geração automática de arquivos PDF para uso administrativo imediato.

3. Justificativa
Dados educacionais isolados em planilhas muitas vezes não se traduzem em melhorias reais por falta de braço técnico para analisá-los individualmente. Este sistema automatiza a ponte entre a evidência estatística e a tomada de decisão, permitindo que um gestor receba não apenas um gráfico, mas um cronograma de ações prioritárias.

4. Quais os objetivos?
Otimizar o tempo de diagnóstico das secretarias de educação.

Padronizar os critérios de intervenção pedagógica e de infraestrutura.

Prover soluções acionáveis, transformando problemas complexos (como baixa alfabetização ou teto avariado) em listas de verificação e cronogramas semanais.

5. O que alcançamos?
Conseguimos criar uma ferramenta funcional que entrega um Relatório de Diagnóstico Direto. O resultado final (como visto no log do sistema) apresenta:

Diagnóstico técnico preciso.

Mapeamento de problemas críticos.

Ações imediatas de alta prioridade.

Checklist de execução.

Cronograma estimado de implementação.

In [ ]:
!pip install requests python-dotenv transformers

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [ ]:
!pip install requests huggingface_hub python-dotenv

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.7.1)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)

In [ ]:
!pip install reportlab

Collecting reportlab
  Downloading reportlab-4.4.10-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.6)
Downloading reportlab-4.4.10-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 23.5 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.10

In [ ]:
import requests
from huggingface_hub import InferenceClient
from google.colab import userdata

MODEL_ID = "Qwen/Qwen2.5-7B-Instruct"
TOKEN = userdata.get('HUGGING_FACE_HUB_TOKEN')

In [ ]:
import pandas as pd
df = pd.read_csv('/content/TS_ALUNO_2EF.csv', sep=';')

print("✅ CSV carregado")
print(df.shape)

✅ CSV carregado
(37104, 55)

In [ ]:
df_escolas = df.groupby("ID_ESCOLA").agg({
    "PROFICIENCIA_LP_SAEB": "mean",
    "IN_ALFABETIZADO": "mean"
}).reset_index()

display(df_escolas.head())

   ID_ESCOLA  PROFICIENCIA_LP_SAEB  IN_ALFABETIZADO
0   61398250            746.384800         0.363636
1   61398260            741.415053         0.476190
2   61398287            725.200576         0.432432
3   61398414            760.078372         0.500000
4   61398419            770.073043         0.760000

In [ ]:
def listar_escolas(df_escolas, limite=10):
    base = df_escolas.sort_values(by="PROFICIENCIA_LP_SAEB")
    print("🏫 Escolas mais críticas:\n")
    display(base.head(limite))

In [ ]:
def gerar_contexto_automatico(media, taxa):

    contexto = ""

    if media < 500:
        contexto += "Desempenho muito baixo no SAEB. "
    elif media < 600:
        contexto += "Desempenho abaixo da média. "
    else:
        contexto += "Desempenho adequado. "

    if taxa < 0.5:
        contexto += "Baixa taxa de alfabetização. "
    else:
        contexto += "Boa taxa de alfabetização. "

    return contexto

In [ ]:
def gerar_diagnostico_escola(nome, nota, infraestrutura, contexto):

    client = InferenceClient(
        model=MODEL_ID,
        token=TOKEN
    )

    prompt = f"""
    Você é um especialista em gestão educacional com foco em INTERVENÇÃO PRÁTICA.

    REGRAS:
    - NÃO seja genérico
    - Use exatamente os dados fornecidos
    - Transforme cada problema em ação direta

    Escola: {nome}
    Nota: {nota}
    Infraestrutura: {infraestrutura}
    Contexto: {contexto}

    FORMATO:

    1. Diagnóstico direto
    2. Problemas
    3. Ações imediatas (alta prioridade)
    4. Checklist
    5. Cronograma
    6. Score de risco (0 a 10)

    Se faltar algo (ex: cadeira), diga explicitamente para resolver.
    """

    response = client.chat_completion(
        messages=[
            {"role": "user", "content": prompt}
        ],
        max_tokens=800,
        temperature=0.3
    )

    return response.choices[0].message.content

In [ ]:
def gerar_relatorio_hibrido(df_escolas, id_escola, infraestrutura_user, contexto_user):

    escola = df_escolas[df_escolas["ID_ESCOLA"] == id_escola]

    if escola.empty:
        return "❌ Escola não encontrada"

    media = escola["PROFICIENCIA_LP_SAEB"].values[0]
    taxa = escola["IN_ALFABETIZADO"].values[0]

    contexto_auto = gerar_contexto_automatico(media, taxa)

    contexto_final = f"""
    {contexto_auto}
    {contexto_user}
    """

    return gerar_diagnostico_escola(
        nome=f"Escola {id_escola}",
        nota=media / 100,
        infraestrutura=infraestrutura_user,
        contexto=contexto_final
    )

In [ ]:
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

def salvar_pdf(relatorio, id_escola):

    nome = f"relatorio_{id_escola}_{datetime.now().strftime('%H%M%S')}.pdf"

    doc = SimpleDocTemplate(nome)
    styles = getSampleStyleSheet()

    conteudo = [Paragraph(linha, styles["Normal"]) for linha in relatorio.split("\n")]

    doc.build(conteudo)

    print(f"📄 PDF salvo: {nome}")

In [ ]:
historico = []

def salvar_historico(id_escola, relatorio):
    historico.append({
        "id": id_escola,
        "relatorio": relatorio,
        "data": datetime.now()
    })

def ver_historico():
    for h in historico:
        print(h["id"], h["data"])

In [ ]:
print("🎓 Sistema Final com IA + CSV + PDF + Histórico\n")

while True:

    listar_escolas(df_escolas)

    id_escola = input("\n🏫 ID da escola (ou sair): ")

    if id_escola == "sair":
        break

    if not id_escola.isdigit():
        print("❌ inválido")
        continue

    infraestrutura = input("🏗️ Infraestrutura: ")
    contexto = input("🌍 Contexto: ")

    print("\n⏳ Gerando...\n")

    relatorio = gerar_relatorio_hibrido(
        df_escolas,
        int(id_escola),
        infraestrutura,
        contexto
    )

    print(relatorio)

    salvar_pdf(relatorio, id_escola)
    salvar_historico(id_escola, relatorio)

    print("\n" + "="*60)

    opcao = input("hist / continuar: ")

    if opcao == "hist":
        ver_historico()

🎓 Sistema Final com IA + CSV + PDF + Histórico

🏫 Escolas mais críticas:

      ID_ESCOLA  PROFICIENCIA_LP_SAEB  IN_ALFABETIZADO
1157   61470633            631.707442             0.00
205    61411959            637.356434             0.00
353    61421750            646.890090             0.00
289    61418771            655.887879             0.00
229    61412989            663.533479             0.00
564    61436506            665.316942             0.00
114    61405341            665.385494             0.00
1175   61471355            665.624871             0.00
809    61451079            667.690530             0.00
1148   61470388            668.533307             0.05

⏳ Gerando...

1. **Diagnóstico direto**
   - A Escola 61470633 apresenta um desempenho adequado, mas com baixa taxa de alfabetização, indicando uma necessidade de melhoria na qualidade do ensino. A infraestrutura precária (teto caindo, ausência de janelas, mobiliário deficiente e inundações) afeta negativamente o ambiente de aprendizagem, o que pode contribuir para a baixa taxa de alfabetização.

2. **Problemas**
   - Teto caindo
   - Ausência de janelas (jmesa)
   - Mobiliário deficiente (somente cadeiras)
   - Inundações durante a chuva
   - Baixa taxa de alfabetização

3. **Ações imediatas (alta prioridade)**
   - **Segurança imediata**: Solicitar a interdição da escola até que as condições de segurança sejam corrigidas.
   - **Reparos urgentes**: Contratar uma empresa especializada para realizar os reparos necessários no teto e instalar janelas (jmesas).
   - **Mobiliário**: Adquirir mobiliário adequado (mesas e cadeiras de tamanho adequado para a idade dos alunos).
   - **Prevenção de inundações**: Implementar medidas de prevenção de inundações, como drenagem adequada e elevação do mobiliário.

4. **Checklist**
   - [ ] Solicitar interdição da escola
   - [ ] Contratar empresa para reparos no teto e instalação de janelas
   - [ ] Adquirir mobiliário adequado
   - [ ] Implementar medidas de prevenção de inundações
   - [ ] Avaliar e melhorar o programa de alfabetização

5. **Cronograma**
   - **Semana 1**: Solicitar interdição da escola e contratar empresa para reparos.
   - **Semana 2-3**: Realizar reparos no teto e instalação de janelas.
   - **Semana 4-5**: Adquirir mobiliário adequado.
   - **Semana 6-7**: Implementar medidas de prevenção de inundações.
   - **Semana 8-12**: Avaliar e melhorar o programa de alfabetização.

6. **Score de risco (0 a 10)**
   - 8: A situação é crítica e requer ação imediata. A infraestrutura precária e a baixa taxa de alfabetização representam riscos significativos para a aprendizagem dos alunos.
📄 PDF salvo: relatorio_61470633_161653.pdf

============================================================